import { Navbar } from "./components/Navbar"
import "./globals.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen w-screen overflow-x-hidden m-0 p-0">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
